#ifndef SLVN_INPUT_H
#define SLVN_INPUT_H

#include <core.h>
#include <debug.h>
#include <WinUser.h>

typedef enum
{
	SLVN_LMOUSE = VK_LBUTTON,
	SLVN_RMOUSE = VK_RBUTTON,
	SLVN_CANCEL = VK_CANCEL,
	SLVN_MMOUSE = VK_MBUTTON,
	SLVN_BACK = VK_BACK,
	SLVN_TAB = VK_TAB,
	SLVN_CLEAR = VK_CLEAR,
	SLVN_SHIFT = VK_SHIFT,
	SLVN_CONTROL = VK_CONTROL,
	SLVN_ALT = VK_MENU,
	SLVN_PAUSE = VK_PAUSE,
	SLVN_CAPS = VK_CAPITAL,
	SLVN_ESC = VK_ESCAPE,
	SLVN_SPACE = VK_SPACE,
	SLVN_PGUP = VK_PRIOR,
	SLVN_PGDOWN = VK_NEXT,
	SLVN_END = VK_END,
	SLVN_HOME = VK_HOME,
	SLVN_LEFT = VK_LEFT,
	SLVN_UP = VK_UP,
	SLVN_RIGHT = VK_RIGHT,
} SLVN_KEYCODE;

SLVN_EXTERN_BEGIN
SLVN_RESULT		SLVN_API	slvn_input_get_async_key(SLVN_KEYCODE keycode);
SLVN_EXTERN_END



#endif // SLVN_INPUT_H